title: Ken Fussner
description: My Personal Blog
author: Ken Fussner
baseurl: ""
url: ""
github: https://github.com/kenfussner

baseurl: ""
url: "http://ken.fussner.us"

disqus_shortname: kenfussner
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]